<?php

namespace Database\Seeders;

use App\Models\Centros;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CentroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Centros::insert([
            ['cent_id' => 1, 'cent_nombre' => 'NINGUNO', 'cent_reg_id_fk' => 1],
            ['cent_id' => 9101, 'cent_nombre' => 'CENTRO DE LOS RECURSOS NATURALES RENOVABLES - LA SALADA', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9103, 'cent_nombre' => 'CENTRO PARA EL DESARROLLO AGROECOLOGICO Y AGROINDUSTRIAL', 'cent_reg_id_fk' => 8],
            ['cent_id' => 9104, 'cent_nombre' => 'CENTRO AGROEMPRESARIAL Y MINERO', 'cent_reg_id_fk' => 13],
            ['cent_id' => 9105, 'cent_nombre' => 'CENTRO INTERNACIONAL NÁUTICO, FLUVIAL Y PORTUARIO', 'cent_reg_id_fk' => 13],
            ['cent_id' => 9110, 'cent_nombre' => 'CENTRO DE DESARROLLO AGROPECUARIO Y AGROINDUSTRIAL', 'cent_reg_id_fk' => 15],
            ['cent_id' => 9111, 'cent_nombre' => 'CENTRO MINERO', 'cent_reg_id_fk' => 15],
            ['cent_id' => 9112, 'cent_nombre' => 'CENTRO PARA LA FORMACION CAFETERA', 'cent_reg_id_fk' => 17],
            ['cent_id' => 9113, 'cent_nombre' => 'CENTRO AGROPECUARIO', 'cent_reg_id_fk' => 19],
            ['cent_id' => 9114, 'cent_nombre' => 'CENTRO BIOTECNOLOGICO DEL CARIBE', 'cent_reg_id_fk' => 20],
            ['cent_id' => 9115, 'cent_nombre' => 'CENTRO AGROPECUARIO Y DE BIOTECNOLOGIA EL PORVENIR', 'cent_reg_id_fk' => 23],
            ['cent_id' => 9116, 'cent_nombre' => 'CENTRO DE FORMACION AGROINDUSTRIAL', 'cent_reg_id_fk' => 41],
            ['cent_id' => 9117, 'cent_nombre' => 'CENTRO AGROINDUSTRIAL DEL META', 'cent_reg_id_fk' => 50],
            ['cent_id' => 9118, 'cent_nombre' => 'CENTRO ACUICOLA Y AGROINDUSTRIAL DE GAIRA', 'cent_reg_id_fk' => 47],
            ['cent_id' => 9119, 'cent_nombre' => 'CENTRO DE FORMACIÓN PARA EL DESARROLLO RURAL Y MINERO', 'cent_reg_id_fk' => 54],
            ['cent_id' => 9120, 'cent_nombre' => 'CENTRO AGROINDUSTRIAL', 'cent_reg_id_fk' => 63],
            ['cent_id' => 9121, 'cent_nombre' => 'CENTRO ATENCION SECTOR AGROPECUARIO', 'cent_reg_id_fk' => 66],
            ['cent_id' => 9122, 'cent_nombre' => 'CENTRO ATENCION SECTOR AGROPECUARIO', 'cent_reg_id_fk' => 68],
            ['cent_id' => 9123, 'cent_nombre' => 'CENTRO AGROPECUARIO LA GRANJA', 'cent_reg_id_fk' => 73],
            ['cent_id' => 9124, 'cent_nombre' => 'CENTRO AGROPECUARIO DE BUGA', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9125, 'cent_nombre' => 'CENTRO LATINOAMERICANO DE ESPECIES MENORES', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9126, 'cent_nombre' => 'CENTRO NAUTICO PESQUERO DE BUENAVENTURA', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9127, 'cent_nombre' => 'CENTRO DE FORMACION PROFESIONAL MINERO AMBIENTAL', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9201, 'cent_nombre' => 'CENTRO DE DISEÑO Y MANUFACTURA DEL CUERO', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9202, 'cent_nombre' => 'CENTRO DE FORMACIÓN EN DISEÑO, CONFECCIÓN Y MODA.', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9203, 'cent_nombre' => 'CENTRO PARA EL DESARROLLO DEL HABITAT Y LA CONSTRUCCIÓN', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9204, 'cent_nombre' => 'CENTRO DE TECNOLOGÍA DE LA MANUFACTURA AVANZADA.', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9205, 'cent_nombre' => 'CENTRO TECNOLÓGICO DEL MOBILIARIO', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9206, 'cent_nombre' => 'CENTRO TEXTIL Y DE GESTIÓN INDUSTRIAL', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9207, 'cent_nombre' => 'CENTRO NACIONAL COLOMBO ALEMAN', 'cent_reg_id_fk' => 8],
            ['cent_id' => 9208, 'cent_nombre' => 'CENTRO INDUSTRIAL Y DE AVIACION', 'cent_reg_id_fk' => 8],
            ['cent_id' => 9209, 'cent_nombre' => 'CENTRO DE TECNOLOGIAS PARA LA CONSTRUCCION Y LA MADERA', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9210, 'cent_nombre' => 'CENTRO DE ELECTRICIDAD, ELECTRÓNICA Y TELECOMUNICACIONES', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9211, 'cent_nombre' => 'CENTRO DE GESTION INDUSTRIAL', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9212, 'cent_nombre' => 'CENTRO DE MANUFACTURA EN TEXTILES Y CUERO', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9213, 'cent_nombre' => 'CENTRO DE TECNOLOGIAS DEL TRANSPORTE', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9214, 'cent_nombre' => 'CENTRO METALMECANICO', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9215, 'cent_nombre' => 'CENTRO DE MATERIALES Y ENSAYOS', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9216, 'cent_nombre' => 'CENTRO DE DISEÑO Y METROLOGIA', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9217, 'cent_nombre' => 'CENTRO PARA LA INDUSTRIA DE LA COMUNICACIÓN GRAFICA', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9218, 'cent_nombre' => 'CENTRO PARA LA INDUSTRIA PETROQUIMICA', 'cent_reg_id_fk' => 13],
            ['cent_id' => 9219, 'cent_nombre' => 'CENTRO DE AUTOMATIZACION INDUSTRIAL', 'cent_reg_id_fk' => 17],
            ['cent_id' => 9220, 'cent_nombre' => 'CENTRO DE PROCESOS INDUSTRIALES', 'cent_reg_id_fk' => 17],
            ['cent_id' => 9221, 'cent_nombre' => 'CENTRO DE TELEINFORMATICA Y PRODUCCIÓN INDUSTRIAL', 'cent_reg_id_fk' => 19],
            ['cent_id' => 9222, 'cent_nombre' => 'CENTRO INDUSTRIAL Y DE ENERGIAS ALTERNATIVAS', 'cent_reg_id_fk' => 44],
            ['cent_id' => 9223, 'cent_nombre' => 'CENTRO DE DISEÑO E INNOVACIÓN TECNOLOGICA INDUSTRIAL', 'cent_reg_id_fk' => 66],
            ['cent_id' => 9224, 'cent_nombre' => 'CENTRO INDUSTRIAL DE MANTENIMIENTO INTEGRAL', 'cent_reg_id_fk' => 68],
            ['cent_id' => 9225, 'cent_nombre' => 'CENTRO INDUSTRIAL DEL DISEÑO Y LA MANUFACTURA', 'cent_reg_id_fk' => 68],
            ['cent_id' => 9226, 'cent_nombre' => 'CENTRO DE INDUSTRIA Y CONSTRUCCION', 'cent_reg_id_fk' => 73],
            ['cent_id' => 9227, 'cent_nombre' => 'CENTRO DE ELECTRICIDAD Y AUTOMATIZACION INDUSTRIAL - CEAI', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9228, 'cent_nombre' => 'CENTRO DE LA CONSTRUCCION', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9229, 'cent_nombre' => 'CENTRO DE DISEÑO TECNOLOGICO INDUSTRIAL', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9230, 'cent_nombre' => 'CENTRO NACIONAL DE ASISTENCIA TECNICA A LA INDUSTRIA - ASTIN', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9231, 'cent_nombre' => 'CENTRO PARA EL DESARROLLO TECNOLÓGICO DE LA CONSTRUCCIÓN Y LA INDUSTRIA', 'cent_reg_id_fk' => 63],
            ['cent_id' => 9232, 'cent_nombre' => 'CENTRO INDUSTRIAL Y DESARROLLO EMPRESARIAL DE SOACHA', 'cent_reg_id_fk' => 25],
            ['cent_id' => 9301, 'cent_nombre' => 'CENTRO DE COMERCIO', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9302, 'cent_nombre' => 'CENTRO DE COMERCIO Y SERVICIOS', 'cent_reg_id_fk' => 8],
            ['cent_id' => 9303, 'cent_nombre' => 'CENTRO DE GESTION DE MERCADOS, LOGISTICA Y TECNOLOGIAS DE LA INFORMACION', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9304, 'cent_nombre' => 'CENTRO DE COMERCIO Y SERVICIOS', 'cent_reg_id_fk' => 13],
            ['cent_id' => 9305, 'cent_nombre' => 'CENTRO DE GESTION ADMINISTRATIVA Y FORTALECIMIENTO EMPRESARIAL', 'cent_reg_id_fk' => 15],
            ['cent_id' => 9306, 'cent_nombre' => 'CENTRO DE COMERCIO Y SERVICIOS', 'cent_reg_id_fk' => 17],
            ['cent_id' => 9307, 'cent_nombre' => 'CENTRO DE COMERCIO Y SERVICIOS', 'cent_reg_id_fk' => 19],
            ['cent_id' => 9308, 'cent_nombre' => 'CENTRO DE COMERCIO Y SERVICIOS', 'cent_reg_id_fk' => 66],
            ['cent_id' => 9309, 'cent_nombre' => 'CENTRO DE SERVICIOS EMPRESARIALES Y TURISTICOS', 'cent_reg_id_fk' => 68],
            ['cent_id' => 9310, 'cent_nombre' => 'CENTRO DE COMERCIO Y SERVICIOS', 'cent_reg_id_fk' => 73],
            ['cent_id' => 9311, 'cent_nombre' => 'CENTRO DE GESTION TECNOLÓGICA DE SERVICIOS', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9401, 'cent_nombre' => 'CENTRO DE SERVICIOS DE SALUD', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9402, 'cent_nombre' => 'CENTRO DE SERVICIOS Y GESTION EMPRESARIAL', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9403, 'cent_nombre' => 'CENTRO DE FORMACION DE TALENTO HUMANO EN SALUD', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9404, 'cent_nombre' => 'CENTRO DE GESTION ADMINISTRATIVA', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9405, 'cent_nombre' => 'CENTRO DE SERVICIOS FINANCIEROS', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9406, 'cent_nombre' => 'CENTRO NACIONAL DE HOTELERIA, TURISMO Y ALIMENTOS', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9501, 'cent_nombre' => 'COMPLEJO TECNOLOGICO PARA LA GESTION AGROEMPRESARIAL', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9502, 'cent_nombre' => 'COMPLEJO TECNOLÓGICO MINERO AGROEMPRESARIAL', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9503, 'cent_nombre' => 'CENTRO DE LA INNOVACIÒN, LA AGROINDUSTRIA Y EL TURISMO', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9504, 'cent_nombre' => 'COMPLEJO TECNOLOGICO AGROINDUSTRIAL, PECUARIO Y TURISTICO', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9508, 'cent_nombre' => 'CENTRO DE FORMACIÓN EN ACTIVIDAD FÍSICA Y CULTURA', 'cent_reg_id_fk' => 11],
            ['cent_id' => 9509, 'cent_nombre' => 'CENTRO DE DESARROLLO AGROINDUSTRIAL Y EMPRESARIAL', 'cent_reg_id_fk' => 25],
            ['cent_id' => 9510, 'cent_nombre' => 'CENTRO AGROECOLOGICO Y EMPRESARIAL', 'cent_reg_id_fk' => 25],
            ['cent_id' => 9511, 'cent_nombre' => 'CENTRO DE LA TECNOLOGIA DEL DISEÑO Y LA PRODUCTIVIDAD EMPRESARIAL', 'cent_reg_id_fk' => 25],
            ['cent_id' => 9512, 'cent_nombre' => 'CENTRO DE BIOTECNOLOGIA AGROPECUARIA', 'cent_reg_id_fk' => 25],
            ['cent_id' => 9513, 'cent_nombre' => 'CENTRO DE DESARROLLO AGROEMPRESARIAL', 'cent_reg_id_fk' => 25],
            ['cent_id' => 9514, 'cent_nombre' => 'CENTRO INDUSTRIAL DE MANTENIMIENTO Y MANUFACTURA', 'cent_reg_id_fk' => 15],
            ['cent_id' => 9515, 'cent_nombre' => 'CENTRO PECUARIO Y AGROEMPRESARIAL', 'cent_reg_id_fk' => 17],
            ['cent_id' => 9516, 'cent_nombre' => 'CENTRO TECNOLOGICO DE LA AMAZONIA', 'cent_reg_id_fk' => 18],
            ['cent_id' => 9517, 'cent_nombre' => 'CENTRO PARA LA BIODIVERSIDAD Y EL TURISMO DEL AMAZONAS', 'cent_reg_id_fk' => 91],
            ['cent_id' => 9518, 'cent_nombre' => 'CENTRO AGROFORESTAL Y ACUICOLA ARAPAIMA', 'cent_reg_id_fk' => 86],
            ['cent_id' => 9519, 'cent_nombre' => 'CENTRO AGROINDUSTRIAL Y FORTALECIMIENTO EMPRESARIAL DE CASANARE', 'cent_reg_id_fk' => 85],
            ['cent_id' => 9520, 'cent_nombre' => 'CENTRO AGROEMPRESARIAL', 'cent_reg_id_fk' => 20],
            ['cent_id' => 9521, 'cent_nombre' => 'CENTRO DE OPERACIÓN Y MANTENIMIENTO MINERO', 'cent_reg_id_fk' => 20],
            ['cent_id' => 9522, 'cent_nombre' => 'CENTRO DE RECURSOS NATURALES, INDUSTRIA Y BIODIVERSIDAD', 'cent_reg_id_fk' => 27],
            ['cent_id' => 9523, 'cent_nombre' => 'CENTRO DE COMERCIO, INDUSTRIA Y TURISMO DE CORDOBA', 'cent_reg_id_fk' => 23],
            ['cent_id' => 9524, 'cent_nombre' => 'CENTRO AGROEMPRESARIAL Y ACUICOLA', 'cent_reg_id_fk' => 44],
            ['cent_id' => 9525, 'cent_nombre' => 'CENTRO AGROEMPRESARIAL Y DESARROLLO PECUARIO DEL HUILA', 'cent_reg_id_fk' => 41],
            ['cent_id' => 9526, 'cent_nombre' => 'CENTRO DE DESARROLLO AGROEMPRESARIAL Y TURISTICO DEL HUILA', 'cent_reg_id_fk' => 41],
            ['cent_id' => 9527, 'cent_nombre' => 'CENTRO DE LA INDUSTRIA, LA EMPRESA Y LOS SERVICIOS', 'cent_reg_id_fk' => 41],
            ['cent_id' => 9528, 'cent_nombre' => 'CENTRO DE GESTION Y DESARROLLO SOSTENIBLE SURCOLOMBIANO', 'cent_reg_id_fk' => 41],
            ['cent_id' => 9529, 'cent_nombre' => 'CENTRO DE LOGISTICA Y PROMOCION ECOTURISTICA DEL MAGDALENA', 'cent_reg_id_fk' => 47],
            ['cent_id' => 9530, 'cent_nombre' => 'CENTRO DE GESTION Y DESARROLLO AGROINDUSTRIAL DE ARAUCA', 'cent_reg_id_fk' => 81],
            ['cent_id' => 9531, 'cent_nombre' => 'CENTRO DE PRODUCCIÓN Y TRANSFORMACION AGROINDUSTRIAL DE LA ORINOQUIA', 'cent_reg_id_fk' => 99],
            ['cent_id' => 9532, 'cent_nombre' => 'CENTRO DE INDUSTRIA Y SERVICIOS DEL META', 'cent_reg_id_fk' => 50],
            ['cent_id' => 9533, 'cent_nombre' => 'CENTRO DE DESARROLLO AGROINDUSTRIAL, TURISTICO Y TECNOLOGICO DEL GUAVIARE', 'cent_reg_id_fk' => 95],
            ['cent_id' => 9534, 'cent_nombre' => 'CENTRO SUR COLOMBIANO DE LOGÍSTICA INTERNACIONAL', 'cent_reg_id_fk' => 52],
            ['cent_id' => 9535, 'cent_nombre' => 'CENTRO AGROINDUSTRIAL Y PESQUERO DE LA COSTA PACIFICA', 'cent_reg_id_fk' => 52],
            ['cent_id' => 9536, 'cent_nombre' => 'CENTRO INTERNACIONAL DE PRODUCCIÓN LIMPIA - LOPE', 'cent_reg_id_fk' => 52],
            ['cent_id' => 9537, 'cent_nombre' => 'CENTRO DE LA INDUSTRIA, LA EMPRESA Y LOS SERVICIOS', 'cent_reg_id_fk' => 54],
            ['cent_id' => 9538, 'cent_nombre' => 'CENTRO DE COMERCIO Y TURISMO', 'cent_reg_id_fk' => 63],
            ['cent_id' => 9539, 'cent_nombre' => 'CENTRO DE FORMACION TURISTICA,  GENTE DE MAR Y DE SERVICIOS', 'cent_reg_id_fk' => 88],
            ['cent_id' => 9540, 'cent_nombre' => 'CENTRO INDUSTRIAL Y DEL DESARROLLO TECNOLOGICO', 'cent_reg_id_fk' => 68],
            ['cent_id' => 9541, 'cent_nombre' => 'CENTRO AGROTURISTICO', 'cent_reg_id_fk' => 68],
            ['cent_id' => 9542, 'cent_nombre' => 'CENTRO DE LA INNOVACION, LA TECNOLOGIA Y LOS SERVICIOS', 'cent_reg_id_fk' => 70],
            ['cent_id' => 9543, 'cent_nombre' => 'CENTRO DE TECNOLOGIAS AGROINDUSTRIALES', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9544, 'cent_nombre' => 'CENTRO DE BIOTECNOLOGIA INDUSTRIAL', 'cent_reg_id_fk' => 76],
            ['cent_id' => 9545, 'cent_nombre' => 'CENTRO AGROEMPRESARIAL Y TURISTICO DE LOS ANDES', 'cent_reg_id_fk' => 68],
            ['cent_id' => 9546, 'cent_nombre' => 'CENTRO DE GESTION AGROEMPRESARIAL DEL ORIENTE', 'cent_reg_id_fk' => 68],
            ['cent_id' => 9547, 'cent_nombre' => 'CENTRO AMBIENTAL Y ECOTURISTICO DEL NORORIENTE AMAZONICO', 'cent_reg_id_fk' => 94],
            ['cent_id' => 9548, 'cent_nombre' => 'CENTRO AGROPECUARIO Y DE SERVICIOS AMBIENTALES JIRI - JIRIMO', 'cent_reg_id_fk' => 97],
            ['cent_id' => 9549, 'cent_nombre' => 'COMPLEJO TECNOLOGICO, TURISTICO Y AGROINDUSTRIAL DEL OCCIDENTE ANTIOQUEÑO', 'cent_reg_id_fk' => 5],
            ['cent_id' => 9551, 'cent_nombre' => 'Centro de la Innovación Agroindustrial y de Servicios', 'cent_reg_id_fk' => 15]
        ]);
    }
}
